### ISSUE TITLE
[vault-secret-webhooks] helm stuck in PENDING_INSTALL

### ISSUE THREAD

**Issue by lantier** [banzaicloud/banzai-charts#888] opened 2019-07-16 16:28 UTC
Hi!

When deploying the **vault-secrets-webhook** chart with Helm and following the README instructions, even if it seens deployed, for helm the release is status is stuck as `PENDING_INSTALL`.

Looking into tiller logs I found the following:
```
[storage/driver] 2019/07/16 16:17:56 update: failed to update: Internal error occurred: failed calling webhook "configmaps.vault-secrets-webhook.admission.banzaicloud.com": Post https://vault-vault-secrets-webhook.vault.svc:443/configmaps?timeout=30s: no endpoints available for service "vault-vault-secrets-webhook"
[tiller] 2019/07/16 16:17:56 warning: Failed to update release vault: Internal error occurred: failed calling webhook "configmaps.vault-secrets-webhook.admission.banzaicloud.com": Post https://vault-vault-secrets-webhook.vault.svc:443/configmaps?timeout=30s: no endpoints available for service "vault-vault-secrets-webhook"
```

I'm installing the **vault-secrets-webhook** charts with the following command:

```
helm upgrade --namespace vault --install vault banzaicloud-stable/vault-secrets-webhook --debug
```

And I have too a namespace vault with the label `name=vault`
```kubectl get ns vault --show-labels
NAME    STATUS   AGE     LABELS
vault   Active   4d21h   name=vault
```

Any tips about it? 
I tried to search in another issues but can't find the same problem with the except the label thing and recursive dependencies between MutationWebhook and the service in question

**Comment by bonifaido** [comment] 2019-07-17 08:45
Hi @lantier, I think you have found a bug in the installation process (which is becoming more harder with Helm, from time to time).

The issue is that Helm tries to create its ConfigMap where it stores the release data about this release, but the WebHookConfiguration is already present which tries to mutate ConfigMaps as well, but the process which backs the Service defined in the WebHookConfiguration isn't running yet. The solution is the following, install with `--wait` flag. In this case Helm will wait for all the resources to come up in a healthy state before writing out the release ConfigMap.

I will update the README to add this instruction.

**Comment by bonifaido** [comment] 2019-07-17 11:16
The README change has been merged @lantier, please feel free to reopen if it doesn't work for you, I have tested it several times and seems bot be working. Thanks for reporting this.

**Comment by lantier** [comment] 2019-07-17 12:15
Hi!
I tried with the wait flag with no success:

```
helm upgrade --namespace vswh --install vswh banzaicloud-stable/vault-secrets-webhook --wait
Release "vswh" does not exist. Installing it now.
NAME:   vswh
LAST DEPLOYED: Wed Jul 17 09:12:53 2019
NAMESPACE: vswh
STATUS: PENDING_INSTALL

RESOURCES:
==> v1/ClusterRole
NAME                        AGE
vswh-vault-secrets-webhook  32s

==> v1/ClusterRoleBinding
NAME                                AGE
vswh-vault-secrets-webhook-limited  32s

==> v1/Deployment
NAME                        READY  UP-TO-DATE  AVAILABLE  AGE
vswh-vault-secrets-webhook  1/1    1           1          32s

==> v1/Pod(related)
NAME                                         READY  STATUS   RESTARTS  AGE
vswh-vault-secrets-webhook-67b7957d4d-ncrl8  1/1    Running  0         32s

==> v1/Secret
NAME                        TYPE    DATA  AGE
vswh-vault-secrets-webhook  Opaque  3     32s

==> v1/Service
NAME                        TYPE       CLUSTER-IP    EXTERNAL-IP  PORT(S)  AGE
vswh-vault-secrets-webhook  ClusterIP  10.105.21.68  <none>       443/TCP  32s

==> v1/ServiceAccount
NAME                        SECRETS  AGE
vswh-vault-secrets-webhook  1        32s

==> v1beta1/MutatingWebhookConfiguration
NAME                        AGE
vswh-vault-secrets-webhook  32s
```
```
helm ls --all
NAME                                    REVISION        UPDATED                         STATUS          CHART                                   APP VERSION     NAMESPACE 
vswh                                    1               Wed Jul 17 09:12:53 2019        PENDING_INSTALL vault-secrets-webhook-0.3.18            0.4.17          vswh      
```

**Comment by bonifaido** [comment] 2019-07-17 13:24
What Helm and Kubernetes version are you using? I can't reproduce, but I have tried only KIND and Docker for Mac Kubernetes.

**Comment by lantier** [comment] 2019-07-17 18:49
Helm 2.14.2 
Kubernetes v1.13.7

We use GKE.

After I saw your message I tried with Docker for Mac I had success, however in Minikube I reproduce the same error

**Comment by bonifaido** [comment] 2019-07-18 07:17
I just tried again with Helm 2.14.2 on Docker for Mac (1.10), GKE (1.13), KIND (1.15), Minikube (1.14) still, no success reproducing this. I will look for other ways to reproduce this.

**Comment by bonifaido** [comment] 2019-07-18 09:50
@lantier my next solution for this quiz :), please check the description of the PR https://github.com/banzaicloud/banzai-charts/pull/890

**Closed** 2019-07-18 09:57 UTC
Labels: bug, vault

**Comment by lantier** [comment] 2019-07-18 14:30
@bonifaido I think it's something GKE related, like some API or config in API server that is conflicting somehow with the Helm install..

I tried a bit further and:

- Recreated K8S GKE cluster from scratch without nothing except tiller: Fail
In tiller logs I saw this:
```
[storage/driver] 2019/07/18 14:12:36 update: failed to update: Timeout: request did not complete within requested timeout 30s
[tiller] 2019/07/18 14:12:36 warning: Failed to update release vswh: Timeout: request did not complete within requested timeout 30s
```
It's surprising because I used `--wait` with `--timeout 300` and the timeout is still 30

I tried too:
- Docker for mac
- Minikube
- EKS

All of them are installed in a couple of secs (mostly 4 or 5) without problems. Only GKE has this problem.

Reading some issues in Helm repo I found that the client may have some problems in different SOs, so I tried helm 2.13.1 and 2.14.2 in: MacOS Mojave (my daily driver), Ubuntu 18.04 and Cloud Shell from GCP.
Same results...

It's really annoying. I tried some old chart version (0.3.10) and it was a success, even if I had other type of problems in this version (that was my reason to upgrade in the first place).
Too much was altered from 3.10 to this 3.19/20 ?

**Comment by bonifaido** [comment] 2019-07-18 15:23
Could you please try to copy the chart change the failurePolicy for the ConfigMaps to Ignore in the WebHookConfiguration and try installing that? That was my original last resort, so we can still use that solution.

**Comment by lantier** [comment] 2019-07-18 16:06
I'll try it in a bit and report here as soon as I can

**Comment by lantier** [comment] 2019-07-18 16:56
@bonifaido 
I tried your suggestion and failed again...
I tried a bit more and removed the whole configMap configuration from the admissionController and guess what? 

It worked! But I think it is a bit worse than your last resort

**Comment by bonifaido** [comment] 2019-07-18 17:05
Yes, that is something that we don't want to do. :) When the timeout happened what was the state (Running?, logs, etc...) of the webhook pod?

**Comment by lantier** [comment] 2019-07-18 17:20
The pod seems to work fine, the problem is the HELM return. It is forever in "PENDING_INSTALL", consequently every upgrade needs to be a `--purge` and install again.

```
time="2019-07-18T17:17:29Z" level=warning msg="no metrics recorder active"
time="2019-07-18T17:17:29Z" level=warning msg="no tracer active"
time="2019-07-18T17:17:29Z" level=warning msg="no metrics recorder active"
time="2019-07-18T17:17:29Z" level=warning msg="no tracer active"
time="2019-07-18T17:17:29Z" level=warning msg="no metrics recorder active"
time="2019-07-18T17:17:29Z" level=warning msg="no tracer active"
time="2019-07-18T17:17:29Z" level=info msg="Listening on :8443"
```

Pod log. 
Nothing wrong in the in the kubernetes events too, only with tiller as mentioned before.

I'll be trying to do some deployment using the webhook as is to verify the behavior of the whole app.

**Comment by bonifaido** [comment] 2019-07-19 07:36
I wonder if you have any network policies or things like that (or maybe some garbage from a previous installation), I have just created a brand new GKE cluster with Kubernetes version 1.13.7-gke.8 and I still can't reproduce this issue.

**Comment by bonifaido** [comment] 2019-07-19 19:40
@lantier I messed up the readinessProbe indentation here as you can see. Please check https://github.com/banzaicloud/banzai-charts/commit/46d11011f214d5da4cde93605f49619b0aa0ecb8#commitcomment-34375973
Could you please try with the correcting the indentation at you locally? A PR will arrive shortly from @jharlow1 thank you!

**Comment by bonifaido** [comment] 2019-07-20 04:54
`banzaicloud-stable/vault-secrets-webhook 0.3.21` is the new version containing the redinessProbe fix (of the fix).

**Comment by lantier** [comment] 2019-07-23 13:41
Wow...
After so much trouble I think finally found the answer.

We're using a Private GKE Cluster, and these type of cluster are limited by VPC Peering between masters and nodes on GKE. GKE creates a rule passing traffic between the API Server and Nodes in ports 443 and 10250 but **NOT in 8843** (wich vault-secrets-webhook uses).

I created a new rule permiting traffic from private master ins port 8443 and all goes well now.

Note: **service.internalPort** set doesn't change the service inside the pod to another port other than 8443 (I tried it before open the rule)

Anyways, thanks so much for all the patience and help.
Think we may have a note for private clusters?

**Comment by bonifaido** [comment] 2019-07-23 14:43
Nice catch @lantier, I think that we need to stick to something other than 443 because we employ PodSecurityPolicies, which doesn't allow the use of privileged ports, please see: https://github.com/banzaicloud/bank-vaults/commit/6ffe86a0766976356ac36c16506ea5a7bb570827
Would you please add the note that you mentioned? That makes a lot of sense. 

Thanks!
